
# mariaDB
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    url: jdbc:mariadb://localhost:3306/gdsc
    password: qndnjs753!

  # JPA
  jpa:
    properties:
      hibernate:
        show-sql: 'true'
        format_sql: 'true'
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: DEBUG